### ISSUE TITLE
traceback when accessing a detailed record page

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#1585]
From time to time, I see the following traceback when accessing a record page such as `http://0.0.0.0/record/4901`. The error is gone after page reload.  Perhaps this happens after populating when a record is accessed for the first time? To be checked.

```
web_1            | Error on request:
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
web_1            |     execute(self.server.app)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
web_1            |     application_iter = app(environ, start_response)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
web_1            |     return self.wsgi_app(environ, start_response)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/werkzeug/wsgi.py", line 660, in __call__
web_1            |     return app(environ, start_response)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
web_1            |     response = self.handle_exception(e)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
web_1            |     reraise(exc_type, exc_value, tb)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
web_1            |     response = self.full_dispatch_request()
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
web_1            |     rv = self.handle_user_exception(e)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
web_1            |     reraise(exc_type, exc_value, tb)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
web_1            |     rv = self.dispatch_request()
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
web_1            |     return self.view_functions[rule.endpoint](**req.view_args)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/invenio_records_ui/views.py", line 170, in record_view
web_1            |     pid, record = resolver.resolve(pid_value)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/invenio_pidstore/resolver.py", line 61, in resolve
web_1            |     pid = PersistentIdentifier.get(self.pid_type, pid_value)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/invenio_pidstore/models.py", line 210, in get
web_1            |     return cls.query.filter_by(**args).one()
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2814, in one
web_1            |     ret = self.one_or_none()
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
web_1            |     ret = list(self)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
web_1            |     return self._execute_and_instances(context)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
web_1            |     result = conn.execute(querycontext.statement, self._params)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
web_1            |     return meth(self, multiparams, params)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
web_1            |     return connection._execute_clauseelement(self, multiparams, params)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
web_1            |     compiled_sql, distilled_params
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
web_1            |     context)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
web_1            |     exc_info
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
web_1            |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
web_1            |     context)
web_1            |   File "/usr/local/var/cernopendata/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
web_1            |     cursor.execute(statement, parameters)
web_1            | OperationalError: (psycopg2.OperationalError) terminating connection due to administrator command
web_1            | server closed the connection unexpectedly
web_1            | 	This probably means the server terminated abnormally
web_1            | 	before or while processing the request.
web_1            |  [SQL: 'SELECT pidstore_pid.created AS pidstore_pid_created, pidstore_pid.updated AS pidstore_pid_updated, pidstore_pid.id AS pidstore_pid_id, pidstore_pid.pid_type AS pidstore_pid_pid_type, pidstore_pid.pid_value AS pidstore_pid_pid_value, pidstore_pid.pid_provider AS pidstore_pid_pid_provider, pidstore_pid.status AS pidstore_pid_status, pidstore_pid.object_type AS pidstore_pid_object_type, pidstore_pid.object_uuid AS pidstore_pid_object_uuid \nFROM pidstore_pid \nWHERE pidstore_pid.pid_type = %(pid_type_1)s AND pidstore_pid.pid_value = %(pid_value_1)s'] [parameters: {'pid_type_1': 'recid', 'pid_value_1': u'4901'}]
```

**Comment by ioannistsanaktsidis** [comment]
Closing as not relevant anymore.
