### ISSUE TITLE
installation: xrootd 4.8.0

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#2258]
We have file download problems with xrootd 4.8.0.  

Example:

```console
$ curl http://0.0.0.0:5000/record/5001/files/DemoAnalyzer.cc
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
$ docker-compose -f docker-compose-dev.yml logs web
web_1            | 172.19.0.1 - - [16/Jan/2018 09:11:46] "GET /record/5001/files/DemoAnalyzer.cc HTTP/1.1" 500 -
web_1            | Error on request:
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
web_1            |     execute(self.server.app)
web_1            |   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 199, in execute
web_1            |     for data in application_iter:
web_1            |   File "/usr/lib/python2.7/site-packages/werkzeug/wsgi.py", line 778, in __next__
web_1            |     data = self.file.read(self.buffer_size)
web_1            |   File "/usr/lib/python2.7/site-packages/xrootdpyfs/xrdfile.py", line 193, in read
web_1            |     size=chunksize,
web_1            |   File "/usr/lib64/python2.7/site-packages/XRootD/client/file.py", line 126, in read
web_1            |     status, response = self.__file.read(offset, size, timeout)
web_1            | SystemError: bad format char passed to Py_BuildValue
```

xrootd 4.7.1 works fine, so we can quick-fix by pinning it while we investigate the upgrade...

**Comment by tiborsimko** [comment]
Looking at upgrading to the latest xrootd 4.12.2 version, which will also fix recent build troubles.  (CC @katilp)
