### ISSUE TITLE
CMS: instructions for calculating luminosity for CMS open data

### ISSUE THREAD

**Issue by tpmccauley** [cernopendata/opendata.cern.ch#2845]
Tasks to document:

- ~~installation of brilcalc~~
- differences between VM and Docker installation and usage
- common queries

**Comment by tpmccauley** [comment]
to-do

- [ ] instructions for VM (currently just Docker)
- [ ] add instructions for data and env besides just 2011
- [ ] does cvmfs make installation easier/trivial? currently installer, then conda env, then pip
- [ ] normtag and cvmfs
- [ ] check if there are differences in results between `-c web` option and running from CERN on lxplus
- [ ] more examples of common queries

**Comment by tpmccauley** [comment]
re: 2010 data in VM

- Running `pip install --user brilws` throws several `ValueError` exceptions related to hash types and a final `ImportError: No module named urllib3`
- Cannot fetch brilconda installer script without the using `wget` with `--no-check-certificate` option. `cms-service-lumi.web.cern.ch`'s certificate cannot be verified

**Comment by tpmccauley** [comment]
Same error for Docker container:
```
[16:16:56] cmsusr@2b9ad3ace132 ~ $ pip install brilws
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/bin/pip", line 4, in <module>
    import pip
  File "/home/cmsusr/brilconda/lib/python2.7/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/cmsusr/brilconda/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/cmsusr/brilconda/lib/python2.7/site-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/home/cmsusr/brilconda/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 61, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/cmsusr/brilconda/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
```

**Comment by mattbellis** [comment]
Tom, which docker image is this? I just tried the same thing with CMSSW_5_3_32 and pip was not even in my PATH.

**Comment by tpmccauley** [comment]
> Tom, which docker image is this? I just tried the same thing with CMSSW_5_3_32 and pip was not even in my PATH.

In a docker container I had to use the brilconda installer script rather than cvmfs. Once installed you have `pip` in the `brilconda` environment.

**Comment by mattbellis** [comment]
Ahhh, gotcha. Thanks.

**Comment by tpmccauley** [comment]
Pasting this here for future reference. This is on 2010 Docker container.
```
[13:47:37] cmsusr@2b9ad3ace132 ~ $ python -v -c "import hashlib"
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /home/cmsusr/brilconda/lib/python2.7/site.pyc matches /home/cmsusr/brilconda/lib/python2.7/site.py
import site # precompiled from /home/cmsusr/brilconda/lib/python2.7/site.pyc
# /home/cmsusr/brilconda/lib/python2.7/os.pyc matches /home/cmsusr/brilconda/lib/python2.7/os.py
import os # precompiled from /home/cmsusr/brilconda/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /home/cmsusr/brilconda/lib/python2.7/posixpath.pyc matches /home/cmsusr/brilconda/lib/python2.7/posixpath.py
import posixpath # precompiled from /home/cmsusr/brilconda/lib/python2.7/posixpath.pyc
# /home/cmsusr/brilconda/lib/python2.7/stat.pyc matches /home/cmsusr/brilconda/lib/python2.7/stat.py
import stat # precompiled from /home/cmsusr/brilconda/lib/python2.7/stat.pyc
# /home/cmsusr/brilconda/lib/python2.7/genericpath.pyc matches /home/cmsusr/brilconda/lib/python2.7/genericpath.py
import genericpath # precompiled from /home/cmsusr/brilconda/lib/python2.7/genericpath.pyc
# /home/cmsusr/brilconda/lib/python2.7/warnings.pyc matches /home/cmsusr/brilconda/lib/python2.7/warnings.py
import warnings # precompiled from /home/cmsusr/brilconda/lib/python2.7/warnings.pyc
# /home/cmsusr/brilconda/lib/python2.7/linecache.pyc matches /home/cmsusr/brilconda/lib/python2.7/linecache.py
import linecache # precompiled from /home/cmsusr/brilconda/lib/python2.7/linecache.pyc
# /home/cmsusr/brilconda/lib/python2.7/types.pyc matches /home/cmsusr/brilconda/lib/python2.7/types.py
import types # precompiled from /home/cmsusr/brilconda/lib/python2.7/types.pyc
# /home/cmsusr/brilconda/lib/python2.7/UserDict.pyc matches /home/cmsusr/brilconda/lib/python2.7/UserDict.py
import UserDict # precompiled from /home/cmsusr/brilconda/lib/python2.7/UserDict.pyc
# /home/cmsusr/brilconda/lib/python2.7/_abcoll.pyc matches /home/cmsusr/brilconda/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /home/cmsusr/brilconda/lib/python2.7/_abcoll.pyc
# /home/cmsusr/brilconda/lib/python2.7/abc.pyc matches /home/cmsusr/brilconda/lib/python2.7/abc.py
import abc # precompiled from /home/cmsusr/brilconda/lib/python2.7/abc.pyc
# /home/cmsusr/brilconda/lib/python2.7/_weakrefset.pyc matches /home/cmsusr/brilconda/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /home/cmsusr/brilconda/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /home/cmsusr/brilconda/lib/python2.7/copy_reg.pyc matches /home/cmsusr/brilconda/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /home/cmsusr/brilconda/lib/python2.7/copy_reg.pyc
# /home/cmsusr/brilconda/lib/python2.7/traceback.pyc matches /home/cmsusr/brilconda/lib/python2.7/traceback.py
import traceback # precompiled from /home/cmsusr/brilconda/lib/python2.7/traceback.pyc
# /home/cmsusr/brilconda/lib/python2.7/sysconfig.pyc matches /home/cmsusr/brilconda/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /home/cmsusr/brilconda/lib/python2.7/sysconfig.pyc
# /home/cmsusr/brilconda/lib/python2.7/re.pyc matches /home/cmsusr/brilconda/lib/python2.7/re.py
import re # precompiled from /home/cmsusr/brilconda/lib/python2.7/re.pyc
# /home/cmsusr/brilconda/lib/python2.7/sre_compile.pyc matches /home/cmsusr/brilconda/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /home/cmsusr/brilconda/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /home/cmsusr/brilconda/lib/python2.7/sre_parse.pyc matches /home/cmsusr/brilconda/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /home/cmsusr/brilconda/lib/python2.7/sre_parse.pyc
# /home/cmsusr/brilconda/lib/python2.7/sre_constants.pyc matches /home/cmsusr/brilconda/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /home/cmsusr/brilconda/lib/python2.7/sre_constants.pyc
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/_locale.so", 2);
import _locale # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/_locale.so
# /home/cmsusr/brilconda/lib/python2.7/_sysconfigdata.pyc matches /home/cmsusr/brilconda/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /home/cmsusr/brilconda/lib/python2.7/_sysconfigdata.pyc
# zipimport: found 7 names in /home/cmsusr/brilconda/lib/python2.7/site-packages/docopt-0.6.2-py2.7.egg
# zipimport: found 7 names in /home/cmsusr/brilconda/lib/python2.7/site-packages/prettytable-0.7.2-py2.7.egg
# zipimport: found 7 names in /home/cmsusr/brilconda/lib/python2.7/site-packages/schema-0.3.1-py2.7.egg
# zipimport: found 122 names in /home/cmsusr/brilconda/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg
import encodings # directory /home/cmsusr/brilconda/lib/python2.7/encodings
# /home/cmsusr/brilconda/lib/python2.7/encodings/__init__.pyc matches /home/cmsusr/brilconda/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /home/cmsusr/brilconda/lib/python2.7/encodings/__init__.pyc
# /home/cmsusr/brilconda/lib/python2.7/codecs.pyc matches /home/cmsusr/brilconda/lib/python2.7/codecs.py
import codecs # precompiled from /home/cmsusr/brilconda/lib/python2.7/codecs.pyc
import _codecs # builtin
# /home/cmsusr/brilconda/lib/python2.7/encodings/aliases.pyc matches /home/cmsusr/brilconda/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /home/cmsusr/brilconda/lib/python2.7/encodings/aliases.pyc
# /home/cmsusr/brilconda/lib/python2.7/encodings/ascii.pyc matches /home/cmsusr/brilconda/lib/python2.7/encodings/ascii.py
import encodings.ascii # precompiled from /home/cmsusr/brilconda/lib/python2.7/encodings/ascii.pyc
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
# /home/cmsusr/brilconda/lib/python2.7/hashlib.pyc matches /home/cmsusr/brilconda/lib/python2.7/hashlib.py
import hashlib # precompiled from /home/cmsusr/brilconda/lib/python2.7/hashlib.pyc
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/_hashlib.so", 2);
import logging # directory /home/cmsusr/brilconda/lib/python2.7/logging
# /home/cmsusr/brilconda/lib/python2.7/logging/__init__.pyc matches /home/cmsusr/brilconda/lib/python2.7/logging/__init__.py
import logging # precompiled from /home/cmsusr/brilconda/lib/python2.7/logging/__init__.pyc
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/time.so", 2);
import time # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/time.so
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/cStringIO.so", 2);
import cStringIO # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/cStringIO.so
# /home/cmsusr/brilconda/lib/python2.7/weakref.pyc matches /home/cmsusr/brilconda/lib/python2.7/weakref.py
import weakref # precompiled from /home/cmsusr/brilconda/lib/python2.7/weakref.pyc
# /home/cmsusr/brilconda/lib/python2.7/collections.pyc matches /home/cmsusr/brilconda/lib/python2.7/collections.py
import collections # precompiled from /home/cmsusr/brilconda/lib/python2.7/collections.pyc
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/_collections.so", 2);
import _collections # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/_collections.so
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/operator.so", 2);
import operator # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/operator.so
# /home/cmsusr/brilconda/lib/python2.7/keyword.pyc matches /home/cmsusr/brilconda/lib/python2.7/keyword.py
import keyword # precompiled from /home/cmsusr/brilconda/lib/python2.7/keyword.pyc
# /home/cmsusr/brilconda/lib/python2.7/heapq.pyc matches /home/cmsusr/brilconda/lib/python2.7/heapq.py
import heapq # precompiled from /home/cmsusr/brilconda/lib/python2.7/heapq.pyc
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/itertools.so", 2);
import itertools # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/itertools.so
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/_heapq.so", 2);
import _heapq # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/_heapq.so
import thread # builtin
# /home/cmsusr/brilconda/lib/python2.7/threading.pyc matches /home/cmsusr/brilconda/lib/python2.7/threading.py
import threading # precompiled from /home/cmsusr/brilconda/lib/python2.7/threading.pyc
# /home/cmsusr/brilconda/lib/python2.7/atexit.pyc matches /home/cmsusr/brilconda/lib/python2.7/atexit.py
import atexit # precompiled from /home/cmsusr/brilconda/lib/python2.7/atexit.pyc
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/cmsusr/brilconda/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/_hashlib.so", 2);
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/binascii.so", 2);
import binascii # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/binascii.so
# /home/cmsusr/brilconda/lib/python2.7/struct.pyc matches /home/cmsusr/brilconda/lib/python2.7/struct.py
import struct # precompiled from /home/cmsusr/brilconda/lib/python2.7/struct.pyc
dlopen("/home/cmsusr/brilconda/lib/python2.7/lib-dynload/_struct.so", 2);
import _struct # dynamically loaded from /home/cmsusr/brilconda/lib/python2.7/lib-dynload/_struct.so
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup __main__
# cleanup[1] _collections
# cleanup[1] encodings
# cleanup[1] site
# cleanup[1] sysconfig
# cleanup[1] operator
# cleanup[1] _heapq
# cleanup[1] abc
# cleanup[1] _weakrefset
# cleanup[1] sre_constants
# cleanup[1] re
# cleanup[1] _codecs
# cleanup[1] _struct
# cleanup[1] _warnings
# cleanup[1] zipimport
# cleanup[1] _sysconfigdata
# cleanup[1] encodings.ascii
# cleanup[1] hashlib
# cleanup[1] _locale
# cleanup[1] logging
# cleanup[1] thread
# cleanup[1] keyword
# cleanup[1] atexit
# cleanup[1] signal
# cleanup[1] traceback
# cleanup[1] itertools
# cleanup[1] posix
# cleanup[1] encodings.aliases
# cleanup[1] time
# cleanup[1] exceptions
# cleanup[1] _weakref
# cleanup[1] cStringIO
# cleanup[1] sre_compile
# cleanup[1] threading
# cleanup[1] _sre
# cleanup[1] weakref
# cleanup[1] binascii
# cleanup[1] collections
# cleanup[1] struct
# cleanup[1] codecs
# cleanup[1] sre_parse
# cleanup[1] heapq
# cleanup[2] copy_reg
# cleanup[2] posixpath
# cleanup[2] errno
# cleanup[2] _abcoll
# cleanup[2] types
# cleanup[2] genericpath
# cleanup[2] stat
# cleanup[2] warnings
# cleanup[2] UserDict
# cleanup[2] os.path
# cleanup[2] linecache
# cleanup[2] os
# cleanup sys
# cleanup __builtin__
# cleanup ints: 851 unfreed ints
# cleanup floats: 2 unfreed floats
```

**Comment by tpmccauley** [comment]
For comparison from 2011 container:
```
[13:41:39] cmsusr@a17b2a79d067 ~/CMSSW_5_3_32/src $ python -v -c "import hashlib"
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/site.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/site.py
import site # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/site.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/os.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/os.py
import os # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/os.pyc
import errno # builtin
import posix # builtin
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/posixpath.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/posixpath.py
import posixpath # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/posixpath.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/stat.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/stat.py
import stat # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/stat.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/genericpath.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/genericpath.py
import genericpath # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/genericpath.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/warnings.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/warnings.py
import warnings # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/warnings.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/linecache.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/linecache.py
import linecache # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/linecache.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/types.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/types.py
import types # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/types.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/UserDict.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/UserDict.py
import UserDict # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/UserDict.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/_abcoll.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/_abcoll.py
import _abcoll # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/_abcoll.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/abc.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/abc.py
import abc # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/abc.pyc
# /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/copy_reg.pyc matches /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/copy_reg.py
import copy_reg # precompiled from /opt/cms/slc6_amd64_gcc472/cms/cmssw/CMSSW_5_3_32/external/slc6_amd64_gcc472/bin/../../../../../../external/python/2.6.4/lib/python2.6/copy_reg.pyc
import encodings # directory /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings
# /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/__init__.pyc matches /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/__init__.py
import encodings # precompiled from /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/__init__.pyc
# /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/codecs.pyc matches /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/codecs.py
import codecs # precompiled from /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/codecs.pyc
import _codecs # builtin
# /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/aliases.pyc matches /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/aliases.py
import encodings.aliases # precompiled from /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/aliases.pyc
# /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/ascii.pyc matches /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/ascii.py
import encodings.ascii # precompiled from /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/encodings/ascii.pyc
Python 2.6.4 (r264:75706, May 29 2013, 16:46:49) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
# /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/hashlib.pyc matches /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/hashlib.py
import hashlib # precompiled from /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/hashlib.pyc
dlopen("/opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/lib-dynload/_hashlib.so", 2);
import _hashlib # dynamically loaded from /opt/cms/slc6_amd64_gcc472/external/python/2.6.4/lib/python2.6/lib-dynload/_hashlib.so
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup __main__
# cleanup[1] encodings
# cleanup[1] site
# cleanup[1] abc
# cleanup[1] _codecs
# cleanup[1] _warnings
# cleanup[1] zipimport
# cleanup[1] encodings.ascii
# cleanup[1] codecs
# cleanup[1] hashlib
# cleanup[1] signal
# cleanup[1] posix
# cleanup[1] encodings.aliases
# cleanup[1] exceptions
# cleanup[1] _hashlib
# cleanup[2] copy_reg
# cleanup[2] posixpath
# cleanup[2] errno
# cleanup[2] _abcoll
# cleanup[2] types
# cleanup[2] genericpath
# cleanup[2] stat
# cleanup[2] warnings
# cleanup[2] UserDict
# cleanup[2] os.path
# cleanup[2] linecache
# cleanup[2] os
# cleanup sys
# cleanup __builtin__
# cleanup ints: 19 unfreed ints
# cleanup floats
```

**Comment by tpmccauley** [comment]
To keep up with developments in #2847 I tested brilcalc installation with VMs 1.5.3 and 1.1.4

1.5.3  :+1: 

1.1.4 

- `cmsrel CMSSW_4_2_8` works but gives a warning that developer's area is created for slc5_amd_gcc434 while current OS is SLC7 
- brilws now installs
- `brilcalc --version` throws `ImportError: No module named docopt` (one can install it using pip but yet more ImportErrors are thrown)

**Comment by tpmccauley** [comment]
It occurs to me that it may be a waste of time setting up brilcalc for 2010 environment. After all, one can calculate lumi for any run from any era once it's set up in 2011 environment (?) 

Update: yes. Run 146436 as mentioned [here](http://opendata.cern.ch/docs/cms-virtual-machine-2010) is from the 2010 era and `brilcalc lumi -c web -r 146436` in 2011 VM works :+1:

**Comment by katilp** [comment]
@tpmccauley @caredg Could we have a guide page on this on the portal? If it makes it in time for the release, it would be good. That would be new files in a new  `cernopendata/modules/fixtures/data/docs/cms-guide-luminosity/` (similarly to `cernopendata/modules/fixtures/data/docs/cms-guide-docker/`)

**Comment by caredg** [comment]
I will make the PR for the trigger stuff today (I need to brush up on how to make it properly).  I can have a look at the other parts afterwards.  One thing that I would like to include in the docker is the mention of the possibility to install cvmfs locally and mount it in the container (or install it directly in the container).

**Comment by katilp** [comment]
OK, perfect, I have some updates made to the docker instructions in #2876 (branch docker-updates). You can add them there, or if @tiborsimko merges it then  in master.

**Comment by tpmccauley** [comment]
@katilp @caredg PR is done. Needs review and approval. Fixed CI tests which now pass.
