### ISSUE TITLE
The local setup fails

### ISSUE THREAD

**Issue by katilp** [cernopendata/opendata.cern.ch#3125]
The local setup fails with containers failing continuously:

opendatacernch_web_1:

```
Traceback (most recent call last):

File "/opt/invenio/var/instance/python/bin/cernopendata", line 33, in <module>

sys.exit(load_entry_point('cernopendata', 'console_scripts', 'cernopendata')())

File "/opt/invenio/var/instance/python/bin/cernopendata", line 25, in importlib_load_entry_point

return next(matches).load()

File "/opt/invenio/var/instance/python/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load

module = import_module(match.group('module'))

File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 994, in _gcd_import

File "<frozen importlib._bootstrap>", line 971, in _find_and_load

File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 678, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

File "/code/cernopendata/cli.py", line 10, in <module>

from .modules.datacite.cli import datacite

File "/code/cernopendata/modules/datacite/cli.py", line 37, in <module>

from utils import generate_doi

ModuleNotFoundError: No module named 'utils'

```

and opendatacernch_web-files_1

```
Traceback (most recent call last):

File "/opt/invenio/var/instance/python/bin/cernopendata", line 33, in <module>

sys.exit(load_entry_point('cernopendata', 'console_scripts', 'cernopendata')())

File "/opt/invenio/var/instance/python/bin/cernopendata", line 25, in importlib_load_entry_point

return next(matches).load()

File "/opt/invenio/var/instance/python/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load

module = import_module(match.group('module'))

File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module

return _bootstrap._gcd_import(name[level:], package, level)

File "<frozen importlib._bootstrap>", line 994, in _gcd_import

File "<frozen importlib._bootstrap>", line 971, in _find_and_load

File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

File "<frozen importlib._bootstrap_external>", line 678, in exec_module

File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed


File "/code/cernopendata/cli.py", line 10, in <module>

from .modules.datacite.cli import datacite

File "/code/cernopendata/modules/datacite/cli.py", line 37, in <module>

from utils import generate_doi

ModuleNotFoundError: No module named 'utils'
```

This is a fresh setup following the steps in https://github.com/cernopendata/opendata.cern.ch/blob/master/DEVELOPING.rst#installation

**Comment by tiborsimko** [comment]
Is this with the latest `master` branch? Can you please rebuilt without using Docker cache, just to be sure? For me it works well:

```console
$ git checkout master
$ git fetch upstream
$ git merge --ff-only upstream/master
$ git diff master upstream/master
$ docker pull inveniosoftware/centos7-python:3.6
$ docker-compose -f docker-compose-dev.yml build --no-cache
$ docker-compose -f docker-compose-dev.yml up -d
$ docker exec -i -t opendatacernch_web_1 scripts/populate-instance.sh --skip-records
$ firefox http://localhost:5000/
```

**Comment by katilp** [comment]
Yes, this is with the lates and up to this point it works for me as well. It fails when I want the add records:

```
$ git checkout -b pr-3113 upstream/pr/3113
Updating files: 100% (195/195), done.
Branch 'pr-3113' set up to track remote branch 'pr/3113' from 'upstream'.
Switched to a new branch 'pr-3113'
$ docker exec -i -t opendatacernch_web_1 cernopendata fixtures records -f cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-higgsfourleptons.json cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-higgsfourleptons.json --mode insert-or-replace
Error response from daemon: Container 3267809d2a273777cf2f0f50328f5c09ee5b812a68d95f167edac8b84e2b897f is restarting, wait until the container is running
$ docker-compose -f docker-compose-dev.yml restart web web-files
Restarting opendatacernch_web-files_1 ... done
Restarting opendatacernch_web_1       ... done
$ docker exec -i -t opendatacernch_web_1 cernopendata fixtures records -f cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-higgsfourleptons.json cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-higgsfourleptons.json --mode insert-or-replace
Traceback (most recent call last):
  File "/opt/invenio/var/instance/python/bin/cernopendata", line 33, in <module>
    sys.exit(load_entry_point('cernopendata', 'console_scripts', 'cernopendata')())
  File "/opt/invenio/var/instance/python/bin/cernopendata", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/invenio/var/instance/python/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/cernopendata/cli.py", line 10, in <module>
    from .modules.datacite.cli import datacite
  File "/code/cernopendata/modules/datacite/cli.py", line 37, in <module>
    from utils import generate_doi
ModuleNotFoundError: No module named 'utils'
```

**Comment by tiborsimko** [comment]
The PR 3113 is older than `master`, which explains the failures. You would have to rebase it on top of latest master:

```console
$ git checkout pr-3113
$ git rebase master -i
...
```

**Comment by katilp** [comment]
OK thanks, that helps me a step further. I still get the following error and I cannot see what is wrong in the command:

```
$ docker exec -i -t opendatacernch_web_1 cernopendata fixtures records -f cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-higgsfourleptons.json cernopendata/modules/fixtures/data/records/cms-tools-nanoaod-outreach-dimuon-spectrum.json cernopendata/modules/fixtures/data/records/cms-derived-nanoaod-outreach-higgsfourleptons.json --mode insert-or-replace
Usage: cernopendata fixtures records [OPTIONS]
Try 'cernopendata fixtures records --help' for help.

Error: Missing option '--mode'.  Choose from:
        insert,
        replace,
        insert-or-replace.
```

**Comment by katilp** [comment]
Ah sorry, it was one at the time.

**Comment by katilp** [comment]
It works, I'll close. Thanks!
