### ISSUE TITLE
broken display of detailed record pages

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#3593]
The display of detailed record pages does not work with the current `master` branch tip.

How to reproduce the problem:

```
$ docker pull registry.cern.ch/inveniosoftware/almalinux:1
$ docker compose -f docker-compose-dev.yml down -v
$ sudo git clean -d -ff -x
$ ./scripts/generate-localhost-certificate.sh
$ docker compose -f docker-compose-dev.yml build --no-cache
$ docker compose -f docker-compose-dev.yml up
$ docker exec -i -t opendatacernch-web-1 /code/scripts/populate-instance.sh --skip-records --skip-glossary --skip-docs
$ docker exec -i -t opendatacernch-web-1 cernopendata fixtures records --mode insert -f cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
$ firefox http://127.0.0.1:5000/record/1
```

This gives the following traceback:

```
web-1                    | 172.24.0.1 - - [05/Mar/2024 13:12:38] "GET /record/1 HTTP/1.1" 500 -
web-1                    | Traceback (most recent call last):
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask/app.py", line 2552, in __call__
web-1                    |     return self.wsgi_app(environ, start_response)
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/werkzeug/middleware/dispatcher.py", line 78, in __call__
web-1                    |     return app(environ, start_response)
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask/app.py", line 2532, in wsgi_app
web-1                    |     response = self.handle_exception(e)
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
web-1                    |     response = self.full_dispatch_request()
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
web-1                    |     rv = self.handle_user_exception(e)
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask/app.py", line 1821, in full_dispatch_request
web-1                    |     rv = self.preprocess_request()
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask/app.py", line 2313, in preprocess_request
web-1                    |     rv = self.ensure_sync(before_func)()
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask_limiter/extension.py", line 1028, in _check_request_limit
web-1                    |     raise e
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask_limiter/extension.py", line 1003, in _check_request_limit
web-1                    |     all_limits = self.__filter_limits(
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask_limiter/extension.py", line 884, in __filter_limits
web-1                    |     name = get_qualified_name(view_func) if view_func else ""
web-1                    |   File "/opt/invenio/var/instance/python/lib/python3.9/site-packages/flask_limiter/util.py", line 30, in get_qualified_name
web-1                    |     return f"{callable.__module__}.{callable.__name__}.{callable.__qualname__}"
web-1                    | AttributeError: 'functools.partial' object has no attribute '__qualname__'
```

**Comment by ntarocco** [comment]
It might be related to [this change](https://github.com/inveniosoftware/invenio-app/commit/12902cc8b38b1d11ac2a1a4f7d146c90a24dcd3f). Can you share what is your version of `Flask-Limiter`?

**Comment by tiborsimko** [comment]
> It might be related to [this change](https://github.com/inveniosoftware/invenio-app/commit/12902cc8b38b1d11ac2a1a4f7d146c90a24dcd3f). Can you share what is your version of `Flask-Limiter`?

That may be it. We are using `registry.cern.ch/inveniosoftware/almalinux:1` with Python 3.9.

With invenio-app 1.5.0, Flask-Limiter was 2.9.2 (leading to the issue). 

Pinning invenio-app back to 1.4.0, Flask-Limiter is 1.1.0 (and things work).
