### ISSUE TITLE
installation: unplug unneeded `populate` steps

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/opendata.cern.ch#373]
When installing `opendata.cern.ch` overlay, the last task appears to end in an error:

``` console
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/opendata/bin/bibupload", line 9, in <module>
    load_entry_point('Invenio==1.9999.3.dev20140912125559', 'console_scripts', 'bibupload')()
  File "/home/vagrant/.virtualenvs/opendata/src/invenio/invenio/base/helpers.py", line 50, in decorated_func
    result = f(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/opendata/src/invenio/invenio/legacy/bibupload/scripts/bibupload.py", line 54, in main
    return bibupload_main()
  File "/home/vagrant/.virtualenvs/opendata/src/invenio/invenio/legacy/bibupload/engine.py", line 2701, in main
    task_submit_check_options_fnc=task_submit_check_options)
  File "/home/vagrant/.virtualenvs/opendata/src/invenio/invenio/legacy/bibsched/bibtask.py", line 502, in task_init
    argv = task_get_options(_TASK_PARAMS['task_id'], _TASK_PARAMS['task_name'])
  File "/home/vagrant/.virtualenvs/opendata/src/invenio/invenio/legacy/bibsched/bibtask.py", line 1018, in task_get_options
    out = marshal.loads(res[0][0])
IndexError: tuple index out of range
ERROR: failed execution of /home/vagrant/.virtualenvs/opendata/bin/bibupload 17
```

This makes the installation process to appear as failed.  

However, this last task is a "remainder" from `invenio-demosite` and is not needed to be run for `opendata.cern.ch` at all.  Hence one can simply ignore this error.

This issue is a reminder to "unplug" unneeded `populate` tasks in upstream Invenio package.

**Comment by tiborsimko** [comment]
Note: this will come when we'll move to Invenio v2.2+.

**Comment by tiborsimko** [comment]
Done in COD3.
